name: Node.js CI CD

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    # To push code into ec2 in action runner
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: npm install -g yarn
      - name: Install package
        run: yarn install
      - name: Build code
        run: yarn build
      - name: Restart pm2
        run: npm exec pm2 restart api
      - name: Clean up
        if: always()
        run: npm uninstall -g yarn
